# site settings
title: Dr. Katherine L. Bottenhorn, PhD
subtitle: Research, development, & scicomm, oh my!
email: katie.bottenhorn@gmail.com
description: This is my portfolio for all things research, code, and scicomm.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://arsneaz.github.io
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/62442katieb
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/katherine-bottenhorn-32b41189
  Twitter: https://twitter.com/62442katieb
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
